# Site settings
title: Nick Stocchero
email: nick@stocchero.net
url: https://stocche.ro
description: "Welcome to Nick Stocchero's home on the internet"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 03A9F4 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nick Stocchero
  location: Born/Built In
  social: Around the Web

skills:
  - item: Statistics/Data Science
  - item: Node.js
  - item: Serverless
  - item: Big Data
  - item: Ruby/Rails/Sinatra
  - item: AWS
  - item: SQL
  - item: iOS/Android
  - item: Devops
  - item: Internet of Things
  - item: Git
  - item: Drupal
  - item: Chef
  - item: PHP
  - item: LaTeX

about:
  - item: Bradley University
  - item: Bachelors of Science
  - item: Mathematics Major
  - item: High School Math Teacher
  - item: Community Volunteer 
  - item: CompTIA A+ Certified
  - item: CompTIA Network+ Certified
  - item: Private Pilot
  - item: Napervillian
  - item: Die hard White Sox Fan

social:
  - title: twitter
    url: http://twitter.com/nick123pig
  - title: facebook
    url: http://facebook.com/nick123pig
  - title: github
    url: http://github.com/nick123pig
  - title: google-plus
    url: https://plus.google.com/+NickStocchero
  - title: reddit
    url: https://reddit.com/u/nick123pig
  - title: instagram
    url: http://instagram.com/nick123pig/
  - title: linkedin
    url: https://www.linkedin.com/in/nickstocchero
  - title: quora
    url: https://www.quora.com/Nick-Stocchero
  - title: youtube
    url: https://www.youtube.com/user/nick123pig/videos

address:
  - line: "Naperville & Peoria"
    state: N
  - line: "Madison"
    state: v
  - line: "Washington"
    state: y

# Build settings
markdown: redcarpet
permalink: pretty
